apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
      labels:
        io.kompose.service: db
    spec:
      containers:
        - args:
            - --innodb-use-native-aio=0
          env:
            - name: MYSQL_DATABASE
              value: db
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: example
            - name: MYSQL_USER
              value: user
          image: mariadb:latest
          name: db
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: db-data

